[package]
name = "tauri-mobile-test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
tauri = "2.0.0-alpha.0"

[build-dependencies]
tauri-build = "2.0.0-alpha.0"
